version: "3"

services:
  soit:
    build: 
      context: .
      dockerfile: Dockerfile
    image: soit:latest
    env_file: .env
    container_name: soit
    volumes:
      - ./src:/opt/src
      - ./db/my.db:/opt/db/my.db
    # depends_on:
    #   - db
    ports:
      - "8080:8080"

  db:
    build: ./db
    image: soit-db:latest
    container_name: soit-db
    env_file: .env
    volumes:
      - soit-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  soit-db: